services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      # args:
    ports:
      - "3000:3000"
    # environment:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
