services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_FASTAPI_URL
        - NEXT_PUBLIC_SUPABASE_URL
        - NEXT_PUBLIC_SUPABASE_ANON_KEY
    ports:
      - "3000:3000"
    environment:
      - OPENAP_API_KEY

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - USERNAME
      - PASSWORD
      - URL
      - PORT
      - SECRET_KEY
