services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_FASTAPI_URL
    ports:
      - "3000:3000"
    # environment:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - USERNAME
      - PASSWORD
      - URL
      - PORT
      - SECRET_KEY
