name: CI

on:
  push:

jobs:
  build-test-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io
      IMAGE: ${{ github.event.repository.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          echo "Enter build commands here"
      - name: Test
        run: |
          echo "Enter test commands here"
      - name: SetEnv
        run: |
          VERSION=${GITHUB_SHA::7}
          TAG=$REGISTRY/giccode24/$IMAGE:$VERSION
          echo "TAG=$TAG" >> $GITHUB_ENV
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.TAG }}